#!/bin/bash
FILES=(assignment/auth_client/auth_client.py
    assignment/game_client/game_client.py
    assignment/game_server/game_server.py
    assignment/map_client/map_client.py
    assignment/map_server/map_server.py
    get_new_token)

for f in $FILES
do
    (black "$f" && pylint "$f") || exit 1
done
